config/routes.rb
Ganli::Application.routes.draw do
  captcha_route
  get "/admin" ,to: "admin/admin#index"
  root "pages#index"

  resources :users,only:[:create,:edit,:update]
  resources :sessions, only: [:create, :destroy]
  resources :pages,only:[:show]
  resources :articles,only:[:index,:show] do  
  end
  resources :guest_messages,only:[:create,:new,:index]
  get "/classification/:id",to: "articles#classification",as: "classification"
 
  scope '/register' do
    get "/",to: "register#email_validate_from_user",as: "register"
    #get "/",to: "register#email",as: "register"
    #post "/email_validate",to: "register#email_validate"
    #get "/user_validate",to: "register#email_validate_from_user"
  end

  namespace 'admin' do
    root "admin#index"
    resources :articles do
      collection do
        get 'audit'
      end
      member do
        get 'audit_edit'
        patch 'audit_article'
      end
    end
    resources :classifications
    resources :navigations
    resources :pages
    resources :admin_menus,only: [:index,:new,:create]
    resources :permissions
    resources :groups
    resources :users do
      collection do
        get 'audit'
      end
      member do
        post 'audit_pass'
      end
    end
    resources :affair_form_instance_audit_logs,only:[:index,:new,:create]
    resources :affair_forms do
      collection do
        get 'apply'
        get 'propose'
      end
      resources :affair_form_instances
    end
    resources :affair_form_instances,only:[:show,:destroy] do
      collection do
        get 'list'
      end
      member do
        get 'admin_view'
      end
    end
    resources :documents do
      collection do
        get 'audit'
      end
      member do
        get 'audit_download'
        get 'download'
      end
    end
    resources :friendly_links
    resources :friendly_link_classifications
    resources :lunches
    resources :guest_messages
    resources :left_navs
    resources :messages do
      collection do
        get 'outbox'
        get 'new_message_notice'
        get 'download*path',action: :download,as: :download#,constraints: {path: /[^\/]*/}
        get 'crocodoc*uuid',action: :crocodoc,as: :crocodoc
      end
      member do
        get 'preview'
      end
    end
    
    resources :announcements do
      collection do
        get 'view_index'
      end
    end

    post 'files/imageup',to: 'files#imageup'
    post 'files/fileup',to: 'files#fileup'
    post 'files/imagemanger',to: 'files#imagemanger'
    get 'files/thumb/:imagename',to: 'files#thumb'

  end

  get '/bbs',to: 'bbs/topics#index'
  
  namespace 'bbs' do
    resources :replies,only:[:destroy] do
      member do
        post 'change_status'
      end
    end

    resources :topics do
      collection do
        get 'audit'
        get 'replies_audit'
      end
      member do
        get 'show_content'
        get 'show_reply_content'
        post 'change_status'
      end
      resources :replies do
        collection do
          get 'audit'
        end
        member do
          post 'change_status'
        end
      end
    end
  end

  get '/login',to:'sessions#new'
  get '/profile',to: 'users#profile',as: "profile"
  patch 'edit_profile',to: 'users#edit_profile'
  match '/logout',to:'sessions#destroy',via: :delete

  get '/page/service',to: 'pages#service'
  get '/search',to: 'articles#search',as: "search"
end

app/models/friendly_link.rb
# == Schema Information
#
# Table name: friendly_links
#
#  id                              :integer          not null, primary key
#  name                            :string(255)
#  url                             :string(255)
#  rank                            :integer
#  created_at                      :datetime
#  updated_at                      :datetime
#  friendly_link_classification_id :integer
#

class FriendlyLink < ActiveRecord::Base
	validates :name,:url,:friendly_link_classification,presence: true

	default_scope {
		order(:rank)
	}
	belongs_to :friendly_link_classification
end

app/controllers/admin/friendly_links_controller.rb
class Admin::FriendlyLinksController < Admin::BaseController
	def index
		@friendly_links = FriendlyLink.all
	end

	def new
		@friendlylink = FriendlyLink.new
	end

	def create
		new_link = FriendlyLink.new(friendly_link_params)
		new_link.friendly_link_classification = FriendlyLinkClassification.find params[:friendly_link][:friendly_link_classification]
		
		if new_link.save
			flash[:notice] = "添加成功"
			redirect_to action: :index
		else
			flash[:error] = new_link.errors.full_messages.join(',')
			redirect_to action: :new
		end
	end

	def edit
		@friendlylink = FriendlyLink.find params[:id]
	end

	def update
		link = FriendlyLink.find params[:id]
		link.assign_attributes friendly_link_params
		link.friendly_link_classification = FriendlyLinkClassification.find params[:friendly_link][:friendly_link_classification]

		if link.save
			flash[:notice] = "修改成功"
			redirect_to action: :index
		else
			flash[:error] = link.errors.full_messages.join(',')
			redirect_to edit_admin_friendly_link_path(link)
		end
	end

	def destroy
		FriendlyLink.find(params[:id]).destroy
		flash_notice
		redirect_to action: :index
	end

	private
	def friendly_link_params
		params.require(:friendly_link).permit(:name,:url,:rank)
	end
end

app/helpers/admin/friendly_links_helper.rb
module Admin::FriendlyLinksHelper
end

app/views/admin/friendly_links/_form.html.haml
=form_for [:admin,@friendlylink] do |f|
	%p
		=f.label :name,"名称"
		=f.text_field :name
	%p
		=f.label :url,"链接地址"
		=f.text_field :url
	%p
		=f.label :friendly_link_classification,"所属分类"
		-if @friendlylink.friendly_link_classification
			=f.select :friendly_link_classification,options_for_select(FriendlyLinkClassification.all.collect{|classification| [classification.name,classification.id]},selected: @friendlylink.friendly_link_classification.id)
		-else
			=f.select :friendly_link_classification,options_for_select(FriendlyLinkClassification.all.collect{|classification| [classification.name,classification.id]})
		=link_to "分类管理",admin_friendly_link_classifications_path
	%p
		=f.label :rank,"排序"
		=f.text_field :rank
	%p
		=f.submit "提交",disable_with: '提交中...'

app/views/admin/friendly_links/_friendly_link.html.haml
%tr
	%td
		=friendly_link.id
	%td
		=friendly_link.name
	%td
		=friendly_link.url
	%td
		=friendly_link.friendly_link_classification.name
	%td
		=friendly_link.rank
	%td
		=link_to "<span class='tiny button secondary'>修改</span>".html_safe,edit_admin_friendly_link_path(friendly_link)
		=button_to "删除",{action: "destroy",:id=>friendly_link},method: :delete,data:{confirm:"确定删除 #{friendly_link.name} ?"},class: "tiny button alert"

app/views/admin/friendly_links/index.html.haml
-content_for :actions_button do
	=link_to "新增友情链接",{action: :new},class: "tiny secondary button"
	=link_to "新增友情链接分类",new_admin_friendly_link_classification_path,class: "tiny secondary button"
-if @friendly_links.empty?
	%p
		还没有友情链接
-else
	%table
		%tr
			%td
				ID
			%td
				名称
			%td
				链接地址
			%td
				所属分类
			%td
				排序
			%td
				操作
		=render partial: :friendly_link,collection: @friendly_links